name: CI Pipeline

# Trigger the pipeline on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build & Test
  build_and_test:
    runs-on: ubuntu-latest  # Use Ubuntu (or windows-latest if on Windows)
    
    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2
        
      # Set up .NET Core SDK (use the version you need)
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Specify the .NET version you're using

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore EmployeeService.sln

      # Build the solution
      - name: Build
        run: dotnet build EmployeeService.sln --configuration Release --no-restore

      # Run tests (if you have any test projects)
      - name: Run tests
        run: dotnet test EmployeeService.sln --configuration Release --no-build --verbosity normal
